../mx seq=x3 "pft=if v3.2='BR' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piBR.xls
../mx seq=x3 "pft=if v3.2='--' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/pi--.xls
../mx seq=x3 "pft=if v3.2='AR' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piAR.xls
../mx seq=x3 "pft=if v3.2='US' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piUS.xls
../mx seq=x3 "pft=if v3.2='BE' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piBE.xls
../mx seq=x3 "pft=if v3.2='CO' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piCO.xls
../mx seq=x3 "pft=if v3.2='TR' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piTR.xls
../mx seq=x3 "pft=if v3.2='CA' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piCA.xls
../mx seq=x3 "pft=if v3.2='IT' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piIT.xls
../mx seq=x3 "pft=if v3.2='CH' then v1'|'v2'|'v3'|'v4/ fi" lw=0 now >xls/piCH.xls
